version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 150919
      MYSQL_DATABASE: studentsDb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --default-authentication-plugin=mysql_native_password --require_secure_transport=OFF
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - db-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: courseDB
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 150919
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
  postgres-data:

networks:
  db-net:
